インタプリタの起動とかしない realpath は高速なので, もしあるようであれば realpath や grealpath を使う

diff --git a/bin/pathf b/bin/pathf
--- a/bin/pathf
+++ b/bin/pathf
@@ -8,6 +8,17 @@ print realpath("$1")
 EOF
 }
 
+if which realpath > /dev/null 2>&1 ; then
+  alias realpath='realpath --canonicalize-missing --no-symlinks'
+elif which grealpath > /dev/null 2>&1 ; then
+  alias realpath='grealpath --canonicalize-missing --no-symlinks'
+elif which python > /dev/null 2>&1 ; then
+  alias realpath=_realpath
+else
+  echo "[$0] ERROR: realpath/grealpath/python command not found." 1>&2
+  exit 1
+fi
+
 if [ $# -eq 1 ]; then
   SCRIPT=$1; shift
   BASEPATH=$PWD
@@ -17,7 +28,7 @@ elif [ $# -eq 2 ]; then
     echo ""
     exit 0
   fi
-  BASEPATH=`_realpath "$1"`; shift
+  BASEPATH=`realpath "$1"`; shift
 else
   echo "usage: $0 -[OPTIONS] SCRIPT [BASEPATH]" 1>&2
   exit 1
